In [2]:
import math
import pandas as pd
import pandas_datareader as web
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense,LSTM
import matplotlib.pyplot as plt

In [13]:
df = pd.read_csv("c.csv")
df.sort

,Average Market Capitalization of listed companies during the six months ended 30 June 2020,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Sr. No.,Company name,ISIN,BSE Symbol,BSE 6 month Avg Total Market Cap in (Rs. Crs.),NSE Symbol,NSE 6 month Avg Total Market Cap (Rs. Crs.),MSEI Symbol,MSEI 6 month Avg Total Market Cap in (Rs Crs.),Average of All Exchanges (Rs. Cr.),Categorization as per SEBI Circular dated Oct ...
1,1,RELIANCE INDUSTRIES LTD,INE002A01018,RELIANCE,893835.87,RELIANCE,"8,93,778.21",NaN,NaN,"8,93,807.04",Large Cap
2,2,TATA CONSULTANCY SERVICES LTD.,INE467B01029,TCS,751701.96,TCS,"7,51,744.67",NaN,NaN,"7,51,723.31",Large Cap
3,3,HDFC BANK LTD.,INE040A01034,HDFCBANK,578180.54,HDFCBANK,"5,77,825.75",NaN,NaN,"5,78,003.14",Large Cap
4,4,"HINDUSTAN UNILEVER LTD.,",INE030A01027,HINDUNILVR,472707.64,HINDUNILVR,"4,70,496.23",NaN,NaN,"4,71,601.93",Large Cap
...,...,...,...,...,...,...,...,...,...,...,...
5000,5000,DHANASHREE ELECTRONICS LIMITED,INE413F01016,DEL,0.00,NaN,NaN,NaN,NaN,-,Small Cap
5001,5001,ELLORA TRADING LIMITED,INE560T01015,ELLORATRAD,0.00,NaN,NaN,NaN,NaN,-,Small Cap
5002,5002,VARDHAN CAPITAL & FINANCE LIMITED,INE128G01018,VARDHANCFL,0.00,NaN,NaN,NaN,NaN,-,Small Cap
5003,5003,OCTAVIUS PLANTATIONS LIMITED,INE117S01016,OCTAVIUSPL,0.00,NaN,NaN,NaN,NaN,-,Small Cap
5004,5004,BHARTIA BACHAT LIMITED,INE745R01016,BHARTIA,0.00,NaN,NaN,NaN,NaN,-,Small Cap